In [1]:
import pandas as pd
import numpy as np

In [3]:
test_df = pd.read_csv('data/test_data_no_target.csv', delimiter=';')
test_df.head()

,Group,I1,I2,I3,I4,I5,I6,I7,I8,I9,...,dI49,dI50,dI51,dI52,dI53,dI54,dI55,dI56,dI57,dI58
0,G3,"0,039283602","-0,034382297","-0,040372758","0,090022863","-0,055952942","0,049228792","0,016236327","-0,045864875","0,692038889",...,"-0,377892086","-0,410908257","-0,4174375","-0,220480519","0,002526132","0,124542933","-0,219341446","0,148324265","0,020379011","-0,004968758"
1,G9,"-0,49171284","-0,039484003","-0,043611749","-0,320311784","0,065520424","-0,216313827","-0,366573195","-0,052790325","-0,370449142",...,"0,553798561","0,660504587","0,806","0,781506494","-0,012519164","-0,014168533","0,669341446","0,015032946","0,023410578","0,00703696"
2,G7,"-0,744978606","-0,038270979","-0,038631212","-0,824020601","0,117907124","-1,434879266","-0,707810386","-0,07317615","-1,698336588",...,"0,707251799","0,909110092","0,7380625","-0,024402597","0,032078978","0,095528","0,350732999","-0,149682485","0,005133925","1,135388545"
3,G2,"0,694506862","-0,026038231","-0,038985338","1,892921303","-0,100101948","0,022435913","-0,198047969","-0,050572177","0,208738117",...,"-0,120561151","-0,118926606","-0,13025","-0,000467532","0,002082462","0,0235408","-0,044463851","0,033332299","0,079054274","-0,002624005"
4,G2,"0,207123179","-0,020461894","-0,033451402","-0,010191074","-0,1468122","0,235520936","0,044640252","-0,029061501","0,464285714",...,"-0,672086331","-0,679972477","-1,1369375","-0,78987013","0,00783856","-0,424394133","-0,704341446","0,011888905","0,93628384","-0,015744808"